In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [3]:
my_list

[1, 2, 3]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
mat = np.array(my_mat)

In [8]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np.arange(start, stop, step) --> to get a numpy array

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

to output array of zeros both vectors and matrices --> use np.zeros(number) for a vector of 5 zeros and np.zeros((5, 5)) --> for a 5 x 5 matrix of zeros (First number represents number of rows and the second the columns)

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

linspace --> returns a specified no. of evenly spaced points between two specified values ---> np.linspace(start, stop, no._of_values)

In [15]:
np.linspace(0, 5, 10) # Ten evenly spaces values between 0 and 5 
#--> returns a one dimensional vector

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

np.eye(num) --> identity num * num matrix

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Create array of random numbers -->
np.random.rand(num) ---> returns a one dimensional array of num uniformly distributed values between 0 and 1.

In [17]:
np.random.rand(4)

array([0.14896089, 0.63692198, 0.991817  , 0.22224892])

if two dimensional matrix is needed -->
np.random.rand(num1, num2)

In [18]:
np.random.rand(2, 3)

array([[0.20744884, 0.69787534, 0.88267604],
       [0.02583534, 0.33140692, 0.43457993]])

to input values with normal distribution or gaussian distribution -->
np.random.randn(num)

In [19]:
np.random.randn(5)

array([ 1.21717211,  0.09615005,  0.27864255,  0.09057453, -0.72097707])

In [20]:
np.random.randn(3, 4)

array([[-0.69813501,  0.65008548,  1.19795323, -0.92363446],
       [-0.53663049,  0.86571964,  0.24467963, -0.64379873],
       [ 0.18390432, -0.1505475 ,  0.03965443, -0.40995533]])

To return random integers between a low to a high -->
np.random(low, high, no_of_samples) --> low is inclusive while high is exclusive

In [21]:
np.random.randint(0, 100)

2

In [22]:
np.random.randint(0, 50, 10)

array([18, 46, 37, 12, 15,  8, 43, 12, 29, 31])

In [23]:
# Attributes and methods of a numpy array
arr = np.arange(0, 25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0, 50, 10)

In [26]:
ranarr

array([42, 24, 47,  8,  5, 45, 34, 48, 26, 12])

To change the shape of an array -->
arr.reshape(num1, num2) --> to get a two-dimensional num1 x num2 matrix, where num1 * num2 = size of the array

In [27]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr

array([42, 24, 47,  8,  5, 45, 34, 48, 26, 12])

In [29]:
# to get the max value of an array
ranarr.max()

48

In [30]:
# to get the minimum
ranarr.min()

5

In [31]:
# to get the location of the maximum or minimum values
ranarr.argmax()

7

In [32]:
ranarr.argmin()

4

In [33]:
# to get the shape of an array
arr.shape

(25,)

In [34]:
arr1 = arr.reshape(5, 5)

In [37]:
arr1.shape

(5, 5)

In [41]:
# datatype of values in array
arr.dtype

dtype('int32')

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [6]:
slice_of_arr = arr[:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [8]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [9]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [10]:
arr_copy = arr.copy()

In [11]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
arr_copy[:] = 999

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_copy

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [16]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [17]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d[1][2]

30

In [19]:
arr_2d[0][1]

10

In [20]:
arr_2d[1]

array([20, 25, 30])

In [21]:
arr_2d[1, 2]

30

In [22]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [23]:
arr_2d[:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [25]:
arr = np.arange(11)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
bool_arr = arr > 5

In [28]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [29]:
# Return instances where the boolean arr is true
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [30]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

### ARRAY OPERATIONS

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [38]:
arr + 100 # adding a scalar directly to very elements in the array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [39]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [40]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [41]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [42]:
np.max(arr)

10

In [43]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])